### ISSUE TITLE
Setup Docker compose

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/FaVe#17]
We should have docker compose to spin up our stack.

For now we start the `vectorizer` and `FaVe`. we can add other vectorizers and different modules in future.

**Comment by asabya** [comment]
```
version: '0.0.0'
services:
  vectorizer:
    image: fairdatasociety/huggingface-vectorizer:latest
    ports:
      - 9876:9876
    restart: on-failure:0
    extra_hosts:
      - "host.docker.internal:host-gateway"

  fave:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '1234'
    - --write-timeout
    - 1500m
    - --read-timeout
    - 1500m
    image: fairdatasociety/fave:latest
    ports:
    - 1234:1234
    restart: on-failure:0
    environment:
      BEE_API: <BEE_API_ENDPOINT>
      RPC_API: <BLOCKCHAIN_RPC_ENDPOINT>
      STAMP_ID: <BATCH_ID>
      USER: <FDS_USERNAME>
      PASSWORD: <FDS_PASWORD>
      POD: <POD_NAME>
      VECTORIZER_URL: http://host.docker.internal:9876 
```
